server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://localhost:8081
        # Opcional para versionamiento Avro
        # value.subject.name.strategy: io.confluent.kafka.serializers.subject.TopicRecordNameStrategy

    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      group-id: account-service-group
      properties:
        schema.registry.url: http://localhost:8081
        specific.avro.reader: true

  # MongoDB Configuration
  data:
    mongodb:
      uri: mongodb://localhost:27017/bd-account
