server:
  port: 8096

spring:
  application:
    name: account-service

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://localhost:8081
        auto.register.schemas: true

    consumer:
      group-id: account-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      enable-auto-commit: false
      properties:
        spring.deserializer.value.delegate.class: io.confluent.kafka.serializers.KafkaAvroDeserializer
        schema.registry.url: http://localhost:8081
        specific.avro.reader: true

    listener:
      ack-mode: manual

  data:
    mongodb:
      uri: mongodb://localhost:27017/bd-account

# Topics de Kafka
kafka:
  topics:
    account-validation-request: account-validation-request
    account-validation-response: account-validation-response

logging:
  level:
    root: INFO
    com.ettdata.account_service: DEBUG
    org.apache.kafka: INFO
    io.confluent.kafka: INFO